### PR TITLE
Pr black magic

### PR DESCRIPTION
**Pull request by sainquake**
@beljjay Check schematic, it should correspond to https://black-magic.org/hardware.html Black Magic Probe Mini V2.1 (BMP21)

@PonomarevDA Check firmware comptbility to work with CubeIDE and other tools that we used to.

### CODE REVIEW

**Review by beljjay — APPROVED** [review]

**Review by beljjay — CHANGES_REQUESTED** [review]
image

**Review by PonomarevDA — CHANGES_REQUESTED** [review]
- t-view-top.png is broken
- t-view-bottom.png is broken
- pinout image in readme is not accessible
- does blackmagic supports stm32g0 target?
- should we consider adding [Pixhawk Debug Full](https://docs.px4.io/main/en/debug/swd_debug.html#pixhawk-debug-full) just in case?

**Comment by sainquake** [comment]
TODO:

 -  Add 10 pin connector for new PX4 standart
 - Add switch to disabel 120 ohm https://item.szlcsc.com/3856577.html

**Review by beljjay — DISMISSED** [review]
не нравиться земля но работать думаю будет)

**Review by PonomarevDA — APPROVED** [review]

**Review by beljjay — APPROVED** [review]
земля мне все еще не нравится, но работать должно

**Pull request merged**
